image: 'kavatech/dnslb:0.1.0'
replicas: 3
affinity: {}
debug: true
agents:
  - foo
  - bar
  - baz
dns:
  provider: autodns
  autodns:
    username: CHANGEME
    password: CHANGEME
etcd:
  hosts:
    - 'http://healthd-etcd-0.healthd-etcd:2379'
    - 'http://healthd-etcd-1.healthd-etcd:2379'
    - 'http://healthd-etcd-2.healthd-etcd:2379'
loadbalancers:
  test.nect.space:
    - 'http://127.0.0.1:5080'
    - 'tcp://192.168.1.215:5081'
  foo.bar.nect.space:
    - 'http://127.0.0.1:6080'
    - 'tcp://192.168.1.215:6081'