apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dnslb
spec:
  selector:
    matchLabels:
      name: dnslb 
  serviceName: "dnslb"
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        name: dnslb 
    spec:
      serviceAccountName: dnslb
      affinity:
{{ toYaml .Values.affinity | trim | indent 8}}
      containers:
      - name: dnslb
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5 
        ports:
        - containerPort: 8080
          name: web
        env:
        - name: 'AUTODNS_USERNAME'
          valueFrom:
            secretKeyRef:
              name: 'dnslb'
              key: 'autodns.username'
        - name: 'AUTODNS_PASSWORD'
          valueFrom:
            secretKeyRef:
              name: 'dnslb'
              key: 'autodns.password'
        - name: 'K8S_LOCK_NAMESPACE'
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.image }}
        imagePullPolicy: Always
        args:
        {{- if .Values.debug }}
        - '-debug'
        {{- end}}
        {{- range .Values.etcd.hosts }}
        - '-etcd'
        - '{{ . }}'
        {{- end }}
        {{- range .Values.agents }}
        - '-agent'
        - '{{ . }}'
        {{- end }}
        - '-provider'
        - '{{ .Values.dns.provider }}'
        {{- range $name, $hosts := .Values.loadbalancers }}
        - '-lb'
        - '{{ $name }}={{ $hosts | join ","}}'
        {{- end }}