apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnslb
  namespace: {{ .Release.Namespace }}
  labels:
    app: dnslb
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: dnslb
  namespace: {{ .Release.Namespace }}
  labels:
    app: dnslb
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: dnslb
  labels:
    app: dnslb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dnslb
  namespace: {{ .Release.Namespace }}
subjects:
  - name: dnslb
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
