{
 "title": "Loadbalancing",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Loadbalancing/Failover", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datacenters serving Endpoints",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "etcdcontroller_lb_healthy_endpoints",
     "legendFormat": "{{lb}}"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcdcontroller_lb_total_endpoints",
     "legendFormat": "WANTED {{ lb }}"
    },
    {
     "expr": "etcdcontroller_lb_healthy_endpoints",
     "legendFormat": "UP {{ lb }}"
    }
   ]
  },
  {
   "title": "Healthy Endpoints per Agent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcdcontroller_agent_healthy_endpoints",
     "legendFormat": "{{agent}} ({{pod}})"
    },
    {
     "expr": "sum(etcdcontroller_lb_total_endpoints)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Agents Status Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcdcontroller_agents_status_age",
     "legendFormat": "{{agent}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(etcdcontroller_agents_total)",
     "legendFormat": "Configured Agents"
    },
    { "expr": "max(etcdcontroller_agents_up)", "legendFormat": "Up" },
    {
     "expr": "(max(etcdcontroller_agents_total)/2)+1",
     "legendFormat": "Quorum"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dnscontroller_zone_updates_by_name[1m])",
     "legendFormat": "DNS Updates {{ zone }}"
    },
    {
     "expr": "rate(dnscontroller_lb_updates_total[1m])",
     "legendFormat": "LB Updates ({{ pod }})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcdcontroller_errors_etcd[1m])",
     "legendFormat": "Error Rate etcd ({{pod}})"
    },
    {
     "expr": "rate(dnscontroller_errors_dns[1m])",
     "legendFormat": "Error Rate dns ({{pod}})"
    },
    {
     "expr": "rate(general_errors_total{job='iptableslb'}[1m])",
     "legendFormat": "Error Rate ipt  ({{pod}})"
    }
   ]
  },
  {
   "title": "Nodes serving Loadbalancer (HH)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "general_lb_healthy_endpoints{instance='192.168.4.1:9080'}",
     "legendFormat": "{{ lb }}"
    }
   ]
  },
  {
   "title": "Nodes serving Loadbalancer (BR)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "general_lb_healthy_endpoints{instance='192.168.2.1:9080'}",
     "legendFormat": "{{ lb }}"
    }
   ]
  },
  {
   "title": "Nodes serving Loadbalancer (HV)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "general_lb_healthy_endpoints{instance='192.168.3.1:9080'}",
     "legendFormat": "{{ lb }}"
    }
   ]
  },
  {
   "title": "Loadbalancers (HH)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "general_lb_healthy{instance='192.168.4.1:9080'}",
     "legendFormat": "UP LBs"
    },
    {
     "expr": "general_lb_total{instance='192.168.4.1:9080'}",
     "legendFormat": "Wanted LBs"
    }
   ]
  },
  {
   "title": "Loadbalancers (BR)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "general_lb_healthy{instance='192.168.2.1:9080'}",
     "legendFormat": "UP LBs"
    },
    {
     "expr": "general_lb_total{instance='192.168.2.1:9080'}",
     "legendFormat": "Wanted LBs"
    }
   ]
  },
  {
   "title": "Loadbalancers (HV)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "general_lb_healthy{instance='192.168.3.1:9080'}",
     "legendFormat": "UP LBs"
    },
    {
     "expr": "general_lb_total{instance='192.168.3.1:9080'}",
     "legendFormat": "Wanted LBs"
    }
   ]
  }
 ]
}