apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dnslb
spec:
  endpoints:
  - port: web
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      name: dnslb