apiVersion: v1
kind: Secret
metadata:
  name: dnslb
type: Opaque
data:
{{- if eq .Values.dns.provider "autodns" }}
  autodns.username: '{{ .Values.dns.autodns.username | b64enc }}'
  autodns.password: '{{ .Values.dns.autodns.password | b64enc }}'
{{- end}}